export const localization = {
  nl: {
    blocks: "Blokken",
    noBlocks: "Deze revisie heeft nog geen blokken, voeg deze toe.",
    orderSaved: "De volgorde van de blokken is opgeslagen",
    orderSaving: "De volgorde van de blokken wordt opgeslagen, een moment geduld a.u.b.",
    confirmDeleteBlock: "Weet u zeker dat u dit blok wilt verwijderen?",
    blockDeleted: "Het blok is verwijderd",
    blockDeleting: "Het blok wordt verwijderd, een moment geduld a.u.b.",
    deleteBlockHeader: "Blok verwijderen",
    closeButton: "Sluiten",
    closeHeader: "Curriculum sluiten?",
    closeQuestion: "Weet u zeker dat u deze revisie wilt sluiten?",
    closeWarning: "Daarmee is het curriculum niet meer publiek zichtbaar!",
    closing: "Het curriculum wordt gesloten, een moment geduld a.u.b.",
    closed: "De revisie is nu gesloten en niet meer publiek beschikbaar.",
    closingFailed: "De revisie is niet gesloten omdat deze niet gepubliceerd is.",
    currentRevisionHeader: "Huidige revisie",
    dividedInYears: "Ingedeeld in jaren",
    currentRevision: "Huidige revisie",
    version: "Versie",
    publishedRevision: "Gepubliceerde revisie",
    notAvailable: "Niet aanwezig",
    back: "Terug",
    education: "Onderwijs",
    educationSubTitle: "Beheer van cursussen & lessen",
    curriculums: "Curriculums",
    curriculumLoading: "Curriculum wordt geladen",
    curriculumName: "Curriculum: @name",
    publishButton: 'Publiceren',
    publishDialogHeader: 'Curriculum publiceren?',
    publishDialogContent: 'Weet u zeker dat u deze revisie wilt publiceren?',
    publishDialogVisibleWarning: 'Daarmee wordt deze revisie publiek zichtbaar!',
    publishDialogNote: 'N.B. Het publiceren van een revisie kan een aantal seconden duren.',
    publishing: 'Het curriculum wordt gepubliceerd, een moment geduld a.u.b.',
    published: 'Het curriculum is gepubliceerd.',
    publishingFailed: 'De revisie kon niet worden gepubliceerd. Controleer of de revisie blokken heeft en of alle cursussen in de blokken gepubliceerd zijn.',
    yearsHeader: "Jaren",
    yearOne : "Jaar 1",
    yearLabel: "Jaar @year"
  },
  en: {
    blocks: "Blocks",
    noBlocks: "This revision does not have any blocks yet, please add some.",
    orderSaved: "The order of the blocks has been saved",
    orderSaving: "The order of the blocks is being saved, please wait a moment.",
    confirmDeleteBlock: "Are you sure you want to delete this block?",
    blockDeleted: "The block has been deleted",
    blockDeleting: "The block is being deleted, please wait a moment.",
    deleteBlockHeader: "Delete block",
    closeButton: "Close",
    closeHeader: "Close curriculum?",
    closeQuestion: "Are you sure you want to close this revision?",
    closeWarning: "This will make the curriculum no longer publicly visible!",
    closing: "The curriculum is being closed, please wait a moment.",
    closed: "The revision is now closed and is no longer publicly available.",
    closingFailed: "The revision is not closed because it has not been published.",
    currentRevisionHeader: "Current revision",
    dividedInYears: "Divided in years",
    currentRevision: "Current revision",
    version: "Version",
    publishedRevision: "Published revision",
    notAvailable: "Not available",
    back: "Back",
    education: "Education",
    educationSubTitle: "management of courses & lessons",
    curriculums: "Curriculums",
    curriculumLoading: "Loading curriculum",
    curriculumName: "Curriculum: @name",
    publishButton: 'Publish',
    publishDialogHeader: 'Publish curriculum?',
    publishDialogContent: 'Are you sure you want to publish this revision?',
    publishDialogVisibleWarning: 'This will make the revision publicly visible!',
    publishDialogNote: 'Note: Publishing a revision may take a few seconds.',
    publishing: 'The curriculum is being published, please wait a moment.',
    published: 'The curriculum has been published.',
    publishingFailed: 'The revision could not be published. Please check if the revision has blocks and if all courses in the blocks are published.',
    yearsHeader: "Years",
    yearOne : "Year 1",
    yearLabel: "Year @year"
  }
};
