export const localization = {
  nl: {
    education: 'Onderwijs',
    subTitle: 'beheer van cursussen & lessen',
    loadingCurriculum: 'Curriculum wordt geladen',
    newCurriculum: 'Nieuw curriculum',
    curriculum: 'Curriculum',
    curriculumName: 'Curriculum: @name',
    curriculums: 'Curriculums',
    new: "Nieuw",
    name: "Naam",
    permalink: "Permalink",
    description: "Omschrijving",
    level: "Niveau",
    saving: "Het curriculum wordt opgeslagen, een moment geduld a.u.b.",
    saved: "Het curriculum is opgeslagen. U wordt binnen enkele ogenblikken teruggestuurd naar het overzicht van curriculums.",
    curriculumNameRequired: "Geef een naam van het curriculum op.",
    curriculumNameMinLength: "De naam van het curriculum dient ten minste 3 tekens lang te zijn.",
    curriculumNameMaxLength: "De naam van het curriculum mag maximaal 255 tekens lang zijn.",
    curriculumNameUnique: "Geef een unieke naam op voor dit curriculum.",
    permalinkRequired: "Geef de permalink van het curriculum op.",
    permalinkMinLength: "De permalink van het curriculum dient ten minste 3 tekens lang te zijn.",
    permalinkMaxLength: "De permalink van het curriculum mag maximaal 255 tekens lang zijn.",
    permalinkPattern: "Een permalink mag alleen uit letters, cijfers en een - bestaan.",
    permalinkUnique: "Geef een unieke permalink op voor dit curriculum.",
    descriptionRequired: "Geef een beschrijving van dit curriculum op."
  },
  en: {
    education: 'Education',
    subTitle: 'management of courses & lessons',
    loadingCurriculum: 'Curriculum is loading',
    newCurriculum: 'New curriculum',
    curriculum: 'Curriculum',
    curriculumName: 'Curriculum: @name',
    curriculums: 'Curriculums',
    new: "New",
    name: "Name",
    permalink: "Permalink",
    description: "Description",
    level: "Level",
    saving: "The curriculum is being saved, please wait a moment.",
    saved: "The curriculum has been saved. You will be redirected to the curriculums overview in a few moments.",
    curriculumNameRequired: "Provide a name for the curriculum.",
    curriculumNameMinLength: "The name of the curriculum must be at least 3 characters long.",
    curriculumNameMaxLength: "The name of the curriculum may be no longer than 255 characters.",
    curriculumNameUnique: "Provide a unique name for this curriculum.",
    permalinkRequired: "Provide the permalink for the curriculum.",
    permalinkMinLength: "The permalink for the curriculum must be at least 3 characters long.",
    permalinkMaxLength: "The permalink for the curriculum may be no longer than 255 characters.",
    permalinkPattern: "A permalink may only contain letters, numbers, and a dash (-).",
    permalinkUnique: "Provide a unique permalink for this curriculum.",
    descriptionRequired: "Provide a description for this curriculum."
  }
}
