export const localization = {
  nl: {
    savingTestimony: 'Het getuigenis wordt opgeslagen, een ogenblik geduld a.u.b.',
    testimonySaved: 'Het getuigenis is opgeslagen. U wordt teruggestuurd naar het feedbackoverzicht.',
    provideName: 'U dient een naam op te geven',
    provideTestimony: 'U dient een getuigenis op te geven',
    newTestimony: 'Nieuw getuigenis',
    feedback: 'Feedback',
    whatStudentsThink: 'Wat vinden de studenten',
    testimony: 'Getuigenis',
    displayName: 'Weergavenaam',
    addAsCourseTestimony: 'Toevoegen als cursus-getuigenis',
    addAsGenericTestimony: 'Toevoegen als algemeen getuigenis',
    anonymous: 'Anoniem',
    markFeedbackProcessed: 'Markeer feedback als verwerkt',
    back: 'Terug',
    save: 'Opslaan',
    specifyTestimonyType: 'U dient aan te geven welk type getuigenis het betreft.',
    enrollments: 'Inschrijvingen',
  },
  en: {
    savingTestimony: 'The testimony is being saved, please wait a moment.',
    testimonySaved: 'The testimony has been saved. You will be redirected to the feedback overview.',
    provideName: 'You need to provide a name',
    provideTestimony: 'You need to provide a testimony',
    newTestimony: 'New testimony',
    feedback: 'Feedback',
    whatStudentsThink: 'What students think',
    testimony: 'Testimony',
    displayName: 'Display name',
    addAsCourseTestimony: 'Add as course testimony',
    addAsGenericTestimony: 'Add as generic testimony',
    anonymous: 'Anonymous',
    markFeedbackProcessed: 'Mark feedback as processed',
    back: 'Back',
    save: 'Save',
    specifyTestimonyType: 'You need to specify the type of testimony.',
    enrollments: 'Enrollments',
  }
};
