export const localization = {
  nl: {
    settings: "Instellingen",
    profile: "Profiel",
    settingsAndData: "instellingen & gegevens",
    emailConfirmationMessage: "Je profiel is opgeslagen. Er is een e-mail naar je nieuwe adres gestuurd om te bevestigen dat dit een geldig e-mailadres is. Volg de verdere instructies om je e-mail definitief aan te passen. Tot die tijd blijft je oude e-mailadres bestaan.",
    errorMessage: "Er was een probleem met het opslaan van je profiel. Probeer het opnieuw.",
    profileSettings: "Profiel instellingen",
    emailAddress: "E-mailadres",
    confirmation: "Bevestiging",
    name: "Naam",
    gender: "Geslacht",
    yearOfBirth: "Geboortejaar",
    emailNotifications: "Email notificaties",
    man: "Man",
    woman: "Vrouw",
    daily: "Dagelijks",
    weekly: "Wekelijks",
    direct: "Direct",
    never: "Nooit",
    passwordConfirmMessage: "Om de aanpassingen in je profiel te bevestigen dien je je wachtwoord op te geven.",
    password: "Wachtwoord",
    nameRequired : "Geeft uw naam op.",
    nameMinLength : "U naam dient minimaal 3 tekens lang te zijn.",
    nameMaxLength : "U naam dient maximaal 255 tekens lang te zijn.",
    emailConfirmError : "De bevestiging is niet gelijk aan het e-mailadres",
    yearOfBirthRequired: "Geef uw geboortejaar op.",
    yearOfBirthRange : "U dient een jaartal tussen 1900 en dit jaar op te geven.",
    passwordRequired : "U dient uw wachtwoord op te geven.",
    mailRequired : "U dient uw e-mailadres op te geven.",
    mailInValid : "Geef een geldig e-mailadres op",
    isEmailUnique : "U kunt dit e-mailadres niet gebruiken",
    passwordError : "Het wachtwoord dat je hebt opgegeven is niet correct.",
  },
  en: {
    settings: "Settings",
    profile: "Profile",
    settingsAndData: "settings & data",
    emailConfirmationMessage: "Your profile has been saved. An email has been sent to your new address to confirm it is a valid email address, follow the further instructions to definitively change your email. Until then, your old email address will remain.",
    errorMessage: "There was a problem saving your profile. Please try again.",
    profileSettings: "Profile settings",
    emailAddress: "Email address",
    confirmation: "Confirmation",
    name: "Name",
    gender: "Gender",
    yearOfBirth: "Year of birth",
    emailNotifications: "Email notifications",
    man: "Male",
    woman: "Female",
    daily: "Daily",
    weekly: "Weekly",
    direct: "Direct",
    never: "Never",
    passwordConfirmMessage: "To confirm the changes to your profile, please enter your password.",
    password: "Password",
    nameRequired: "Please enter your name.",
    nameMinLength: "Your name must be at least 3 characters long.",
    nameMaxLength: "Your name must be no more than 255 characters long.",
    emailConfirmError: "The confirmation does not match the email address.",
    yearOfBirthRequired: "Please enter your year of birth.",
    yearOfBirthRange: "You must enter a year between 1900 and this year.",
    passwordRequired: "You must enter your password.",
    mailRequired: "You must enter your email address.",
    mailInValid: "Please enter a valid email address.",
    isEmailUnique: "You cannot use this email address.",
    passwordError: "The password you entered is not correct.",
  }
};
