export const localization = {
  nl: {
    education: "Onderwijs",
    subTitle: "beheer van cursussen & lessen",
    curriculums: "Curriculums",
    curriculumIsLoading: "Curriculum wordt geladen",
    curriculum: "Curriculum: @name",
    revision: "Revisie: @rev",
    year: "Jaar: @year",
    blockNew: "Blok: nieuw blok",
    block: "Blok: @name",
    data: "Gegevens",
    name: "Naam",
    description: "Omschrijving",
    courses: "Cursussen",
    saving: "Het blok wordt opgeslagen, een moment geduld a.u.b.",
    saved: "Het blok is opgeslagen. U wordt binnen enkele ogenblikken teruggestuurd naar het overzicht van blokken.",
    blockMustHaveAtLeastOneCourse: "Een blok dient tenminste 1 cursus te hebben.",
    blockHasNoCourses: "Dit blok heeft nog geen cursussen, selecteer deze.",
    assignedCourses: "Toegekende cursussen",
    ready: "Gereed",
    coursesFor: "Cursussen voor: @block",
    blockNameTooShort: "De naam van het blok dient tenminste 3 tekens lang te zijn.",
    blockNameTooLong: "De naam van het blok mag maximaal 255 tekens lang zijn.",
    blockNameRequired: "Geef een naam voor het blok op.",
    blockNameNotUnique: "Geef een unieke naam op voor dit blok."
  },
  en: {
    education: "Education",
    subTitle: "management of courses & lessons",
    curriculums: "Curriculums",
    curriculumIsLoading: "Curriculum is loading",
    curriculum: "Curriculum: @name",
    revision: "Revision:@rev ",
    year: "Year: @year",
    blockNew: "Block: new block",
    block: "Blok: @name",
    data: "Data",
    name: "Name",
    description: "Description",
    courses: "Courses",
    saving: "The block is being saved, please wait a moment.",
    saved: "The block has been saved. You will be redirected to the block overview in a few moments.",
    blockMustHaveAtLeastOneCourse: "A block must have at least one course.",
    blockHasNoCourses: "This block does not have any courses yet, please select them.",
    assignedCourses: "Assigned courses",
    ready: "Done",
    coursesFor: "Courses for: @block",
    blockNameTooShort: "The block name must be at least 3 characters long.",
    blockNameTooLong: "The block name can be no longer than 255 characters.",
    blockNameRequired: "Provide a name for the block.",
    blockNameNotUnique: "Provide a unique name for this block."
  }
};

