export const localization = {
  nl: {
    save: "Opslaan",
    savingAlert: "Het blog wordt opgeslagen, even geduld aub.",
    savedAlert: "Het blog is opgeslagen.",
    author: "Auteur",
    published: "Gepubliceerd",
    publicationDate: "Publicatie datum",
    name: "Naam",
    permalink: "Permalink",
    content: "Inhoud",
    errorContent: "Fout in inhoud",
    empty: "-",
    blogs: "Blogs",
    blogAdd: "Blog toevoegen",
    blogEdit: "Blog bewerken",
    newsAndBackgrounds: "Nieuws & achtergronden",
    contentValidation: "Geef de inhoud van de blog op.",
    nameValidation: "Geef de naam van de blog op.",
    uniqueNameValidation: "Geef een unieke naam voor deze blog op.",
    permalinkValidation: "Geef de permalink van de blog op.",
    permalinkPatternValidation: "Een permalink mag alleen uit kleine letters, cijfers en een - bestaan.",
    uniquePermalinkValidation: "Geef een unieke permalink voor deze blog op.",

  },
  en: {
    save: "Save",
    savingAlert: "The blog is being saved, please wait.",
    savedAlert: "The blog has been saved.",
    author: "Author",
    published: "Published",
    publicationDate: "Publication Date",
    name: "Name",
    permalink: "Permalink",
    content: "Content",
    errorContent: "Error in content",
    empty: "-",
    blogs: "Blogs",
    blogAdd: "Add blog",
    blogEdit: "Edit blog",
    newsAndBackgrounds: "News & backgrounds",
    contentValidation: "Provide the content of the blog.",
    nameValidation: "Provide the name of the blog.",
    uniqueNameValidation: "Provide a unique name for this blog.",
    permalinkValidation: "Provide the permalink of the blog.",
    permalinkPatternValidation: "A permalink may only consist of lowercase letters, numbers, and a -.",
    uniquePermalinkValidation: "Provide a unique permalink for this blog.",

  }
};
