export const localization = {
  nl: {
    courses: "Cursussen",
    title: "Onderwijs",
    subTitle: "beheer van cursussen & lessen",
    courseLoading: 'Cursus word geladen',
    addCourse: 'Nieuwe cursus toevoegen',
    courseName: "Cursus: @name",
    saving: "De cursus wordt opgeslagen. Vanwege de afbeeldingen kan dit even duren.",
    saved: "De cursus is opgeslagen. U wordt terug gestuurd naar het overzicht van cursussen.",
    stage: "Status",
    name: "Naam",
    permalink: "Permalink",
    maxLessonsDaily: "Max. lessen per dag",
    description: "Omschrijving",
    citation: "Citaat",
    introductionLink: "Introductie video",
    author: "Auteur",
    copyright: "Uitgever",
    copyrightLogo: "Logo Uitgever",
    webshopLink: "Link naar webshop",
    level: "Niveau",
    largeImage: "Grote afbeelding",
    thumbnailImage: "Kleine afbeelding",
    headerImage: "Pagina kop afbeelding",
    isVideoCourse: "Video cursus",
    isPrivate: "Cursus verbergen",
    showOnHomepage: "Weergeven op homepage",
    nameMaxLength: "De naam van een cursus mag maximaal 255 tekens lang zijn.",
    nameMinLength: "De naam van een cursus dient tenminste 3 tekens lang te zijn.",
    nameRequired:  "Geef een naam van de cursus op.",
    nameIsUniqueName: "Geef een unieke naam op voor deze cursus.",
    permalinkRequired: "Geef de permalink van de cursus op.",
    permalinkPattern: "Een permalink mag alleen uit kleine letters, cijfers en een - bestaan.",
    permalinkIsUniquePermalink: "Geef een unieke permalink op voor deze cursus.",
    descriptionRequired: "Geef een beschrijving van de cursus op.",
    authorMaxLength: "De naam van de auteur van een cursus mag maximaal 255 tekens lang zijn.",
    copyrightMaxLength: "De copyright melding kan niet langer zijn dan 255 tekens",
    copyrightLogoMaxLength: "De link naar het logo van cursus uitgever kan niet langer zijn dan 255 tekens",
    notFound: "De cursus is niet gevonden",
    loading: "De cursus wordt geladen",
    cancel : "Annuleren",
    revisions: "Revisies",
    save: "Opslaan"
  },
  en: {
    courses: "Courses",
    title: "Education",
    subTitle: "Management of courses & lessons",
    courseLoading: 'Course is loading',
    addCourse: 'Add new course',
    courseName: "Course: @name",
    saving: "The course is being saved. This may take a while due to the images.",
    saved: "The course has been saved. You will be redirected to the course overview.",
    stage: "Status",
    name: "Name",
    permalink: "Permalink",
    maxLessonsDaily: "Max. lessons per day",
    description: "Description",
    citation: "Citation",
    introductionLink: "Introduction video",
    author: "Author",
    copyright: "Publisher",
    copyrightLogo: "Publisher Logo",
    webshopLink: "Link to webshop",
    level: "Level",
    largeImage: "Large image",
    thumbnailImage: "Small image",
    headerImage: "Header image",
    isVideoCourse: "Video course",
    isPrivate: "Hide course",
    showOnHomepage: "Show on homepage",
    nameMaxLength: "The name of a course may be a maximum of 255 characters long.",
    nameMinLength: "The name of a course must be at least 3 characters long.",
    nameRequired: "Please provide a name for the course.",
    nameIsUniqueName: "Please provide a unique name for this course.",
    permalinkRequired: "Please provide the permalink for the course.",
    permalinkPattern: "A permalink may only consist of lowercase letters, numbers, and a -.",
    permalinkIsUniquePermalink: "Please provide a unique permalink for this course.",
    descriptionRequired: "Please provide a description of the course.",
    authorMaxLength: "The name of the author of a course may be a maximum of 255 characters long.",
    copyrightMaxLength: "The copyright notice cannot be longer than 255 characters.",
    copyrightLogoMaxLength: "The link to the logo of the course publisher may be a maximum of 255 characters long.",
    notFound: "The course could not be found.",
    loading: "The is being loaded",
    cancel : "Cancel",
    revisions: "Revisions",
    save: "Save"
  }
}










