export const localization = {
  nl: {
    blogs: "Blogs",
    newsAndBackgrounds: "nieuws en achtergronden",
    noBlogsFound: "Geen blogs gevonden in het systeem.",
    addBlog: "Blog toevoegen",
    viewStats: "Statistieken bekijken",
    createdOn: "Op",
    byAuthor: "Door",
    title: "Titel",
    permalink: "Permalink",
    author: "Auteur",
    published: "Gepubliceerd",
    publicationDate: "Publicatie datum",
    creationDate: "Aanmaak datum",
    lastModified: "Laatste wijziging",
    convertedToMarkdown: "Omgezet naar MarkDown",
    takeOffline: "Offline halen",
    publish: "Publiceren",
    delete: "Verwijderen",
    confirmDeleteHeader: "Blog verwijderen",
    confirmDeleteContent: "Weet u zeker dat u dit blog wilt verwijderen? Dit kan niet ongedaan gemaakt worden!",
    confirmDeleteButton: "Verwijderen",
    confirmTakeOfflineHeader: "Blog offline halen",
    confirmTakeOfflineContent: "Weet u zeker dat u dit blog offline wilt halen? U kunt het altijd weer (her)publiceren.",
    confirmTakeOfflineButton: "Offline halen",
    confirmPublishHeader: "Blog publiceren",
    confirmPublishContent: "Weet u zeker dat u dit blog wilt publiceren?",
    confirmPublishButton: "Publiceren",
    startDelete: "Het blog wordt verwijderd, een moment geduld a.u.b.",
    completedDelete: "Het blog is verwijderd.",
    startTakeOffline: "Het blog wordt offline gehaald, een moment geduld a.u.b.",
    completedTakeOffline: "Het blog is offline gehaald.",
    startPublish: "Het blog wordt gepubliceerd, een moment geduld a.u.b.",
    completedPublish: "Het blog is nu gepubliceerd.",
  },
  en: {
    blogs: "Blogs",
    newsAndBackgrounds: "news and backgrounds",
    noBlogsFound: "No blogs found in the system.",
    addBlog: "Add Blog",
    viewStats: "View Statistics",
    createdOn: "Created On",
    byAuthor: "By",
    title: "Title",
    permalink: "Permalink",
    author: "Author",
    published: "Published",
    publicationDate: "Publication Date",
    creationDate: "Creation Date",
    lastModified: "Last Modification",
    convertedToMarkdown: "Converted to MarkDown",
    takeOffline: "Take offline",
    publish: "Publish",
    delete: "Delete",
    confirmDeleteHeader: "Delete blog",
    confirmDeleteContent: "Are you sure you want to delete this blog? This cannot be undone!",
    confirmDeleteButton: "Delete",
    confirmTakeOfflineHeader: "Take blog offline",
    confirmTakeOfflineContent: "Are you sure you want to take this blog offline? You can always (re)publish it later.",
    confirmTakeOfflineButton: "Take offline",
    confirmPublishHeader: "Publish blog",
    confirmPublishContent: "Are you sure you want to publish this blog?",
    confirmPublishButton: "Publish",
    startDelete: "The blog is being deleted, please wait a moment.",
    completedDelete: "The blog has been deleted.",
    startTakeOffline: "The blog is being taken offline, please wait a moment.",
    completedTakeOffline: "The blog has been taken offline.",
    startPublish: "The blog is being published, please wait a moment.",
    completedPublish: "The blog is now published.",
  }
};
