export const localization = {
  nl: {
    education: "Onderwijs",
    subTitle: "beheer van cursussen & lessen",
    series: "Series",
    seriesName: "Series: @name",
    seriesLoading: "Serie wordt geladen",
    courses: "Cursussen",
    savingAlert: "De toekenning van de cursussen aan de serie wordt opgeslagen, een moment geduld a.u.b.",
    savedAlert: "De toekenning van de cursussen aan de serie is opgeslagen. U wordt teruggestuurd naar het overzicht van series.",
    availableCourses: "Beschikbare cursussen",
    mandatoryCourses: "Verplichte cursussen",
    seriesHeader: "Cursussen van serie: ",
  },
  en: {
    education: "Education",
    subTitle: "management of courses & lessons",
    series: "Series",
    seriesName: "Series: @name",
    seriesLoading: "Series is loading",
    courses: "Courses",
    savingAlert: "The assignment of the courses to the series is being saved, please wait a moment.",
    savedAlert: "The assignment of the courses to the series has been saved. You will be redirected back to the series overview.",
    availableCourses: "Available courses",
    mandatoryCourses: "Mandatory courses",
    seriesHeader: "Courses of series: @series",
  },
};
