export const localization = {
  nl: {
    new: 'Nieuw',
    seriesName: 'Serie: @name',
    nameLabel: 'Naam',
    descriptionLabel: 'Omschrijving',
    levelLabel: 'Niveau',
    savingMessage: 'De serie wordt opgeslagen, een moment geduld a.u.b.',
    savedMessage: 'De serie is opgeslagen. U wordt binnen enkele ogenblikken teruggestuurd naar het overzicht van series.',
    name: "Naam",
    description: "Omschrijving",
    level: "Niveau",
    saving: "De serie wordt opgeslagen, een moment geduld a.u.b.",
    saved: "De serie is opgeslagen. U wordt binnen enkele ogenblikken teruggestuurd naar het overzicht van series.",
    seriesNameMinLength: 'De naam van de serie dient tenminste 3 tekens lang te zijn.',
    seriesNameMaxLength: 'De naam van de serie mag maximaal 255 tekens lang zijn.',
    seriesNameRequired: 'Geef een naam voor de serie op.',
    seriesNameUnique: 'Geef een unieke naam op voor deze serie.',
    seriesDescriptionMinLength: 'De omschrijving van de serie dient tenminste 3 tekens lang te zijn.',
    seriesDescriptionRequired: 'Geef de omschrijving van de serie op.',
    education: "Onderwijs",
    courseManagement: "beheer van cursussen & lessen",
    seriesList: "Series",
    seriesLoading: "Serie wordt geladen",
    addSeries: "Serie toevoegen",
  },
  en: {
    new: 'New',
    seriesName: 'Serie: @name',
    nameLabel: 'Name',
    descriptionLabel: 'Description',
    levelLabel: 'Level',
    savingMessage: 'The series is being saved, please wait a moment.',
    savedMessage: 'The series has been saved. You will be redirected to the series overview in a few moments.',
    name: "Name",
    description: "Description",
    level: "Level",
    saving: "The series is being saved, please wait a moment.",
    saved: "The series has been saved. You will be redirected to the series overview in a few moments.",
    seriesNameMinLength: 'The series name must be at least 3 characters long.',
    seriesNameMaxLength: 'The series name can be a maximum of 255 characters long.',
    seriesNameRequired: 'Provide a name for the series.',
    seriesNameUnique: 'Provide a unique name for this series.',
    seriesDescriptionMinLength: 'The series description must be at least 3 characters long.',
    seriesDescriptionRequired: 'Provide a description for the series.',
    education: "Education",
    courseManagement: "course & lesson management",
    seriesList: "Series",
    seriesLoading: "Series loading",
    addSeries: "Add series",
  },
};
