export const localization = {
  nl: {
    enrollments: "Inschrijvingen",
    lessonsAndReview: "lessen & nakijken",
    newEnrollment: "Nieuwe inschrijving",
    gradeValidation: "Het cijfer dient tussen de 0 en 10 te liggen.",
    completionDateValidation: "Geef aan wanneer deze inschrijving was voltooid",
    selectStudent: "Selecteer een student",
    student: "Student",
    selectCourse: "Selecteer een cursus",
    course: "Cursus",
    selectMentor: "Selecteer een mentor",
    mentor: "Mentor",
    back: "Terug",
    add: "Toevoegen",
    savingAlert: "De inschrijving wordt nu opgeslagen, een moment geduld a.u.b.",
    savedAlert: "De inschrijving is opgeslagen, u wordt doorgestuurd naar de pagina van de student.",
    completed: "Voltooid",
    grade: "Cijfer",
    date: "Datum",
    onPaper: "Op papier",
  },
  en: {
    enrollments: "Enrollments",
    lessonsAndReview: "Lessons & Review",
    newEnrollment: "New Enrollment",
    gradeValidation: "The grade must be between 0 and 10.",
    completionDateValidation: "Indicate when this enrollment was completed",
    selectStudent: "Select a student",
    student: "Student",
    selectCourse: "Select a course",
    course: "Course",
    selectMentor: "Select a mentor",
    mentor: "Mentor",
    back: "Back",
    add: "Add",
    savingAlert: "The enrollment is being saved, please wait a moment.",
    savedAlert: "The enrollment has been saved, you are being redirected to the student's page.",
    completed: "Completed",
    grade: "Grade",
    date: "Date",
    onPaper: "On paper",
  }
};
