export const localization = {
  nl : {
    title: "Dashboard",
    subTitle: "de getalletjes",
    activeStudents: "Actieve studenten",
    submittedLessons: "Ingeleverde lessen",
    newStudents: "Nieuwe studenten",
    newEnrollments: "Nieuwe inschrijvingen",
    moreInformation: "Meer Informatie",
    moreStatsLink: {
      title: "Detail statistieken",
      courses: "Cursussen",
      blogs: "Blogs",
      mentors: "Mentoren",
      students: "Studenten",
      devices: "Apparaten",
      performance: "Performance",
    },
    moreStats: "Meer statistieken",
    versionInfo: "Versie informatie",
    frontEnd: "Frontend",
    backEnd: "Backend",
    database: "Database",
    totalStudents: "Totaal aantal studenten",
    activeStudentsToday: "Aantal actieve studenten vandaag",
    messagesSendToday: "Berichten verstuurd vandaag",
    totalCompletedLessons: "Totaal aantal voltooide lessen",
    totalCompletedCourses: "Totaal aantal voltooide cursussen",
    activeMentorsToday: "Aantal actieve mentoren vandaag",
    bouncePercentage: "Bounce Percentage",
  },
  en : {
    title: "Dashboard",
    subTitle: "the numbers",
    activeStudents: "Active students",
    submittedLessons: "Submitted lessons",
    newStudents: "New students",
    newEnrollments: "New enrollments",
    moreInformation: "More Information",
    moreStatsLink: {
      title: "Detailed statistics",
      courses: "Courses",
      blogs: "Blogs",
      mentors: "Mentors",
      students: "Students",
      devices: "Devices",
      performance: "Performance",
    },
    moreStats: "More statistics",
    versionInfo: "Version informatie",
    frontEnd: "Frontend",
    backEnd: "Backend",
    database: "Database",
    totalStudents: "Total number of students",
    activeStudentsToday: "Active students today",
    messagesSendToday: "Messages send today",
    totalCompletedLessons: "Total completed lessons",
    totalCompletedCourses: "Total completed courses",
    activeMentorsToday: "Active mentors today",
    bouncePercentage: "Bounce Percentage",
  }
}
