export const localization = {
  nl: {
    incomingFeedback: "Binnengekomen feedback",
    endOfCourseFeedback: "Aan het einde van de cursus krijgen de studenten de mogelijkheden om feedback te geven. Hier onder vind je de laatste ontvangen studenten feedback die je nog niet hebt verwerkt.",
    latestFeedback: "Laatste feedback",
    moreFeedback: "Meer feedback",
    allFeedback: "Alle feedback",
    processed: "Verwerkt",
    goBack: "Ga terug",
    confirmation: "Bevestiging",
    createTestimony: "Getuigenis aanmaken",
    errorOccurred: "Er is een fout opgetreden",
    save: "Opslaan",
    cancel: "Annuleren",
    notProcessed: "Niet verwerkt",
    feedback: "Feedback",
    whatStudentsThink: "Wat vinden de studenten",
    last: "Laatst",
    more: "Meer",
    all: "Alle",
    enrollments: "Inschrijvingen",
  },
  en: {
    incomingFeedback: "Incoming feedback",
    endOfCourseFeedback: "At the end of the course, students are given the opportunity to provide feedback. Below, you will find the latest received student feedback that you have not yet processed.",
    latestFeedback: "Latest feedback",
    moreFeedback: "More feedback",
    allFeedback: "All feedback",
    processed: "Processed",
    notProcessed: "Not Processed",
    goBack: "Go Back",
    confirmation: "Confirmation",
    createTestimony: "Create Testimony",
    errorOccurred: "An error occurred",
    save: "Save",
    cancel: "Cancel",
    feedback: "Feedback",
    whatStudentsThink: "What the students think",
    last: "Last",
    more: "More",
    all: "All",
    enrollments: "Enrollments",
  },
};
