export const localization = {
  nl : {
    users: "Gebruikers",
    header: "Mentoren",
    mentors: "Mentoren",
    title: "Mentorenbeheer",
    subTitle: "Accounts & cursussen",
    noEntities: "Er zijn geen mentoren aanwezig in het systeem.",
    courses: "Cursussen",
    students: "Studenten",
    regions: "regio's",
    name : "Naam",
    gender: "Geslacht",
    email: "E-mail",
    primarySite: "Hoofd-site",
    primaryRegion: "Regio",
    activeStudents: "Actieve studenten",
    preferredStudents: "Gewenst aantal studenten",
    maximumStudents: "Maximum aantal studenten",
    rating: "Waardering",
    hasAccess: "Toegang",
    subscriptionDate: "Aanmeld datum"
  },
  en : {
    users: "Users",
    header: "Mentors",
    mentors: "Mentors",
    title: "Mentor management",
    subTitle: "Accounts & courses",
    noEntities: "No Mentors available",
    courses: "Courses",
    students: "Students",
    regions: "region",
    name : "Name",
    gender: "Gender",
    email: "E-mail",
    primarySite: "Primary site",
    primaryRegion: "Regio",
    activeStudents: "Active students",
    preferredStudents: "Preferred students",
    maximumStudents: "Maximum students",
    rating: "Rating",
    hasAccess: "Has access",
    subscriptionDate: "Subscription date"
  }
}
