export const localization = {
  nl : {
    title : "Statistieken",
    subTitle : "Verwerking & response",
    dashboard: "Dashboard",
    statistics: "Statistieken",
    performance: "Performance",
    processingTime: "Verwerkingstijd",
    calls: "Aanvragen",
    seconds: "sec.",
    processingTimePerWeek: "Gemiddelde verwerkingstijd per week",
    processingTimeLast48: "Verwerkingstijd afgelopen 48 uur",
    day: "Dag",
    hour: "Uur",
    relativeCallsPerDay: "% van aanvragen per dag",
    relativeCallsPerHour: "% van aanvragen per uur",
  },
  en : {
    title : "Statistics",
    subTitle : "Processing & responses",
    dashboard: "Dashboard",
    statistics: "Statistics",
    performance: "Performance",
    processingTime: "Processing time",
    calls: "Requests",
    seconds: "sec.",
    processingTimePerWeek: "Average processing time per week",
    processingTimeLast48: "Processing time past 48 hours",
    day: "Day",
    hour: "Hour",
    relativeCallsPerDay: "% of requests per day",
    relativeCallsPerHour: "% of requests per hour",
  }
}
