export const localization = {
  nl: {
    settings: "Instellingen",
    diagnostics: "Diagnose",
    pushNotifications: "Push Notificaties",
    configuration: "Configuratie",
    settingsAndData: "instellingen & gegevens",
    sendNotification: "Verstuur een notificatie",
    chooseUser: "Kies een gebruiker",
    user: "Gebruiker",
    title: "Titel",
    titlePlaceholder: "Titel",
    message: "Bericht",
    messagePlaceholder: "Inhoud",
    send: "Sturen",
    result: "Resultaat",
    success: "Succes",
    errorMessage: "Foutmelding",
    exception: "Exception",
    back: "Terug",
  },
  en: {
    settings: "Settings",
    diagnostics: "Diagnostics",
    pushNotifications: "Push Notifications",
    configuration: "Configuration",
    settingsAndData: "Settings & Data",
    sendNotification: "Send a notification",
    chooseUser: "Choose a user",
    user: "User",
    title: "Title",
    titlePlaceholder: "Title",
    message: "Message",
    messagePlaceholder: "Content",
    send: "Send",
    result: "Result",
    success: "Success",
    errorMessage: "Error message",
    exception: "Exception",
    back: "Back",
  },
};
