export const localization = {
  nl : {
    title: "Dashboard",
    subTitle: "de getalletjes",
    details : "Details",
    activeStudents : "Actieve studenten",
    homepageVisits : "Homepage bezoekers",
    newEnrollments : "Nieuwe inschrijvingen",
    newStudents : "Nieuwe studenten",
    submittedLessons: "Ingeleverde lessen",
    courseEnrollments: "Cursus Aanmeldingen",
    enrollmentNotCompleted : "Gestopt met cursus",
    maleOrFemale: "Man / Vrouw",
    completed: "Afgerond",
    open: "Open",
    canceled: "Gestopt",
    male: "Man",
    female: "Vrouw",
    sendMessages : "Verstuurde bericht(en)",
    completedCourses: "Voltooide cursussen",
    averageReviewTime: "Nakijkduur, (gem. dagen)",
    totals: "Totalen"
  },
  en : {
    title: "Dashboard",
    subTitle: "the numbers",
    details : "Details",
    activeStudents : "Active students",
    homepageVisits : "Homepage visitors",
    newEnrollments : "New course enrollments",
    newStudents: "New students",
    submittedLessons: "Submitted lessons",
    courseEnrollments: "Course Enrollments",
    enrollmentNotCompleted : "Course not completed",
    maleOrFemale: "Male / Female",
    completed: "Completed",
    open: "Open",
    canceled: "Canceled",
    male: "Male",
    female: "Female",
    sendMessages : "Send messages",
    completedCourses: "Completed courses",
    averageReviewTime: "Review time, (day avg.)",
    totals: "Overall"
  }
}
