export const localization = {
  nl : {
    title: "Onderwijs",
    subTitle: "beheer van cursussen & lessen",
    courses: "Cursussen",
    prerequisites: "Ingangseisen",
    revisions: "Revisies",
    mentors: "Mentoren",
    edit: "Bewerken",
    deleteButton : {
      confirm: "Weet u zeker dat u deze cursus wilt verwijderen? Alle hieraan gekoppelde informatie word dan verwijderd!",
      deleted: "De cursus is verwijderd",
      deleting: "De curses word verwijderd, een moment geduld a.u.b",
      header: "Cursus verwijderen"
    },
    stage: "Status",
    name: "Naam",
    author: "Auteur",
    copyright: "Copyright",
    copyrightLogo: "Logo",
    webshopLink: "Link naar webshop",
    videoIntroduction: "Video introductie",
    permalink: "Permalink",
    description: "Omschrijving",
    citation: "Citaat",
    level: "Niveau",
    image: "Afbeelding",
    maxLessonSubmissions: "Max. lessen per dag",
    isVideoCourse: "Video cursus",
    private: "Verborgen",
    showOnHomepage: "Op homepage",
    noCourses: "Er zijn nog geen cursussen in het systeem. Maak er één aan.",
    add: "Toevoegen"
  },
  en : {
    title: "Education",
    subTitle: "Management of courses & lessons",
    courses: "Courses",
    prerequisites: "Prerequisites",
    revisions: "Revisions",
    mentors: "Mentors",
    edit: "Edit",
    deleteButton : {
      confirm: "Are you sure you want to remove this course? All lessons of the course will be removed!",
      deleted: "The course is removed.",
      deleting: "The course is being removed, one moment please.",
      header: "Remove course"
    },
    stage: "Stage",
    name: "Name",
    author: "Author",
    copyright: "Copyright",
    copyrightLogo: "Logo",
    webshopLink: "Link to webshop",
    videoIntroduction: "Video introduction",
    permalink: "Permalink",
    description: "Description",
    citation: "Citation",
    level: "Level",
    image: "Image",
    maxLessonSubmissions: "Max. submissions per day",
    isVideoCourse: "Video course",
    private: "Private",
    showOnHomepage: "Show on homepage",
    noCourses: "There are no courses in the system, please add one.",
    add: "Add"
  }
}
