export const localization = {
  nl: {
    settings: "Instellingen",
    password: "Wachtwoord",
    security: "Beveiliging",
    accessAndVerification: "toegang & verificatie",
    changePassword: "Wachtwoord aanpassen",
    currentPassword: "Huidige wachtwoord",
    newPassword: "Nieuw wachtwoord",
    confirmation: "Bevestiging",
    updatingPassword: "Je wachtwoord word bijgewerkt, een moment geduld a.u.b.",
    incorrectPassword: "Het wachtwoord dat je hebt opgegeven is niet correct.",
    passwordUpdated: "Je wachtwoord is bijgewerkt, bij de eerst volgende keer dat je ingelogd dien je het nieuwe wachtwoord te gebruiken.",
    passwordRequired: "Je dient je wachtwoord op te geven.",
    newPasswordRequired: "JGeef je nieuwe wachtwoord op.",
    newPasswordPattern: "'Je nieuwe wachtwoord dien tenminste 8 tekens lang, 1 getal, 1 hoofd- en 1 kleine letter te bevatten.'",
    confirmationRequired: "Geeft de bevestiging van je nieuwe wachtwoord op.",
    confirmationMatch: "De bevestiging van je nieuwe wachtwoord komt niet overeen.",
    savedFailed: "Wachtwoord kon niet worden bijgewerkt.",
  },
  en: {
    settings: "Settings",
    password: "Password",
    security: "Security",
    accessAndVerification: "access & verification",
    changePassword: "Change Password",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmation: "Confirmation",
    updatingPassword: "Your password is being updated, please wait a moment.",
    incorrectPassword: "The password you entered is not correct.",
    passwordUpdated: "Your password has been updated, you will need to use the new password the next time you log in.",
    passwordRequired: "Please enter your current password.",
    newPasswordRequired: "Please enter your new password.",
    newPasswordPattern: "Your new password must be at least 8 characters long and contain 1 number, 1 uppercase and 1 lowercase letter.",
    confirmationRequired: "Please confirm your new password.",
    confirmationMatch: "The confirmation of your new password does not match.",
    savedFailed: "Failed to update password."
  }
};
