export const localization = {
  nl : {
    cancel: "Annuleren",
    title: "Titel",
    url: "Url",
    insert: "Invoegen",
    insertFile: "Bestand invoegen",
    validUrl: "Geef een geldige link op.",
    insertVideo: "@type invoegen",
    insertTable: "Tabel invoegen",
    example: "Voorbeeld",
    rows: "Rijen",
    columns: "Kolommen",
    withHeader: "Met kop",
    collapsedHeader: "Enkelvoudig",
    insertImage: "Afbeelding invoegen",
    alignment: "Uitlijning",
    insertLink: "Link invoegen",
    external: "Extern",
    none: "Breed",
    left: "Links",
    right: "Rechts"
  },
  en : {
    cancel: "Cancel",
    title: "Title",
    url: "Url",
    insert: "Insert",
    insertFile: "Insert file",
    validUrl: "Please provide a valid link.",
    insertVideo: "Insert @type",
    insertTable: "Insert table",
    example: "Example",
    rows: "Rows",
    columns: "Columns",
    withHeader: "With header",
    collapsedHeader: "Single",
    insertImage: "Insert image",
    alignment: "Alignment",
    insertLink: "Insert link",
    external: "External",
    none: "Wide",
    left: "Left",
    right: "Right"
  },
}
