export const localization = {
  nl : {
    cancel: "Annuleren",
    title: "Titel",
    url: "Url",
    insert: "Invoegen",
    insertFile: "Bestand invoegen",
    validUrl: "Geef een geldige link op.",
    insertVideo: "@type invoegen",
    insertTable: "Tabel invoegen",
    example: "Voorbeeld",
    rows: "Rijen",
    columns: "Kolommen",
    withHeader: "Met kop",
    collapsedHeader: "Enkelvoudig",
    insertImage: "Afbeelding invoegen",
    alignment: "Uitlijning",
    insertLink: "Link invoegen",
    external: "Extern",
    none: "Breed",
    left: "Links",
    right: "Rechts"
  },
  en : {
    cancel: "Annuleren",
    title: "Titel",
    url: "Url",
    insert: "Invoegen",
    insertFile: "Bestand invoegen",
    validUrl: "Geef een geldige link op.",
    insertVideo: "@type invoegen",
    insertTable: "Tabel invoegen",
    example: "Example",
    rows: "Rijen",
    columns: "Kolommen",
    withHeader: "Met kop",
    collapsedHeader: "Enkelvoudig",
    insertImage: "Afbeelding invoegen",
    alignment: "Uitlijning",
    insertLink: "Link invoegen",
    external: "Extern",
    none: "Breed",
    left: "Links",
    right: "Rechts"
  },
}
