export const localization = {
  nl : {
    audioDeleteButton : {
      confirm: "Weet u zeker dat u de audio wilt verwijderen.",
      deleted: "De audio is verwijderd",
      deleting: "De audio word verwijderd, een moment geduld a.u.b",
      header: "Audio verwijderen",
    },
    audio: "Audio",
    upload: "Upload",
    choices: "Keuze mogelijkheden",
    noChoicesProvided: "Geen keuze mogelijkheden opgegeven.",
    choice: "Keuze",
    correct: "Correct",
    audioUploadFailed: "Het audio zip bestand is niet correct verwerkt. Probeer het nog eens.",
    heading: "Koptekst",
    number: "Nummer",
    forcePageBreak: "Pagina afbreken",
    title: "Onderwijs",
    subTitle: "beheer van cursussen & lessen",
    edit: "bewerken",
    cancel: "Annuleren",
    ready: "Gereed",
    answer: "Antwoord",
    exactAnswer: "Exact antwoord",
    answerExplanation: "Uitleg van het antwoord",
    question: "Vraag",
    multiCorrect: "Multi correct",
    url : "Url",
    text: "Tekst",
    caption: "Onderschrift",
    image: "Afbeelding",
    description: "Omschrijving",
    readBeforeStart: "Lezen voor les",
    name: "Name",
    content: "Inhoud",
    settings: "Algemene instellingen",
    courses: "Cursussen",
    courseName: "Cursus: @name",
    revisions: "Revisies",
    lessonName: "Les @number: @name",
    newLesson: "Nieuwe les",
    save: "Opslaan",
    saved: "De les is opgeslagen.",
    failed: "Er is een probleem opgetreden bij het opslaan van de les. Probeer het nogmaals. Blijven er problemen optreden neem dan contact op met de ontwikkelaar.",
    saving: "De les wordt opgeslagen, een moment geduld aub.",
    blockValidation : {
      url: 'Geef de url op, deze dient te beginnen met https://',
      youtube: 'Dit is geen geldige url van een YouTube filmpje.',
      vimeo: 'Dit is geen geldige url van een Vimeo filmpje.',
      text: 'Geef de tekst van dit tekst-element op.',
      question: 'Geef de vraag op.',
      choices: 'Controleer of alle keuzes ingevuld zijn.',
      min: 'Geef tenminste 2 keuze mogelijkheden op.',
      multi: 'Geef maximaal 1 keuze aan als correct.',
    },
    lessonValidation : {
      nameRequired : "Geef de naam van de les op",
      nameMinLength : "De naam van een les dient tenminste 3 tekens lang te zijn.",
      nameMaxLength : "De naam van een les mag maximaal 50 tekens lang zijn.",
      numberRequired : "Geef het nummer van de les op.",
      numberMinLength : "Het nummer van een les dient tenminste 1 teken lang te zijn.",
      numberMaxLength : "Het nummer van een les mag maximaal 50 tekens lang zijn."
    }
  },
  en: {
    audioDeleteButton: {
      confirm: "Are you sure you want to delete the audio?",
      deleted: "The audio has been deleted",
      deleting: "The audio is being deleted, please hold on a moment",
      header: "Delete Audio",
    },
    audio: "Audio",
    upload: "Upload",
    choices: "Choices",
    noChoicesProvided: "No choice options provided.",
    choice: "Choice",
    correct: "Correct",
    audioUploadFailed: "Processing the audio zip file failed, please try again.",
    heading: "Heading",
    number: "Number",
    forcePageBreak: "Force page break",
    title: "Education",
    subTitle: "Management of courses & lessons",
    edit: "edit",
    cancel: "Cancel",
    ready: "Accept",
    answer: "Answer",
    exactAnswer: "Exact answer",
    answerExplanation: "Explanation of the answer",
    question: "Question",
    multiCorrect: "Multi correct",
    url : "Url",
    text: "Text",
    caption: "Caption",
    image: "Image",
    description: "Description",
    readBeforeStart: "Read before the lessons",
    name: "Name",
    content: "Contents",
    settings: "Settings",
    courses: "Courses",
    courseName: "Course: @name",
    revisions: "Revisions",
    lessonName: "Lesson @number: @name",
    newLesson: "New lesson",
    saved: "The lesson has been saved.",
    failed: "There was a problem saving the lesson. Please try again. If the problem persists, contact the developer.",
    saving: "The lesson is being saved, please wait a moment.",
    save: "Save",
    blockValidation: {
      url: 'Enter the URL, it must start with https://',
      youtube: 'This is not a valid URL for a YouTube video.',
      vimeo: 'This is not a valid URL for a Vimeo video.',
      text: 'Enter the text for this text element.',
      question: 'Enter the question.',
      choices: 'Make sure all choices are filled in.',
      min: 'Provide at least 2 answer options.',
      multi: 'Mark only 1 option as correct.',
    },
    lessonValidation: {
      nameRequired: "Enter the name of the lesson.",
      nameMinLength: "The name of a lesson must be at least 3 characters long.",
      nameMaxLength: "The name of a lesson may be up to 50 characters long.",
      numberRequired: "Enter the lesson number.",
      numberMinLength: "The lesson number must be at least 1 character long.",
      numberMaxLength: "The lesson number may be up to 50 characters long."
    }
  }
}
