export const localization = {
  nl: {
    details: "Details",
    add: "Nieuw",
    search: "Zoeken",
    settings: "Instellingen",
    diagnosis: "Diagnose",
    subTitle: "Instellingen & gegevens",
    testNotifications: "Test Notificaties",
    testEmail: "Test mail",
    emailSent: "De test e-mail word verstuurd naar het admin account, gelieve deze te controleren.",
    back: "Terug",
    accept: "Accepteren",
    headers: "Header informatie",
    header: "Informatie mbt. headers, cross origin sharing en meer",
    build : "Build",
    release: "Release",
    database: "Database",
    environment: "Omgeving",
    isDevelopmentEnv: "Ontwikkel omgeving",
    adminEmail: "Email Beheerder",
    versionInfo: "Version informatie",
    corsInfo: "CORS informatie",
  },
  en: {
    details: "Details",
    add: "Add",
    search: "Search",
    settings: "Settings",
    subTitle: "Settings & data",
    diagnosis: "Diagnosis",
    configuration: "Configuration",
    testNotifications: "Test Notifications",
    testEmail: "Test mail",
    emailSent: "The test email is being sent to the admin account, please check it.",
    back: "Back",
    accept: "Accept",
    header: "Information on header, cross origin sharing and much more",
    headers: "Header information",
    build : "Build",
    release: "Release",
    database: "Database",
    environment: "Environment",
    isDevelopmentEnv: "Development Environment",
    adminEmail: "Admin Email",
    versionInfo: "Version information",
    corsInfo: "CORS information",
  },
};
