export const localization = {
  nl: {
    save: "Opslaan",
    savingInProgress: "De pagina wordt opgeslagen, even geduld aub.",
    savedSuccess: "De pagina is opgeslagen.",
    pages: "Pagina's",
    addPage: 'Pagina toevoegen',
    informExplain: 'Informeren & uitleggen',
    type: "Type",
    name: "Naam",
    permalink: "Permalink",
    website: "Website",
    published: "Gepubliceerd",
    content: "Inhoud",
    errorContent: "Gelieve te controleren of er inhoud is voor deze pagina",
    aboutUs: "Over ons",
    individualPage: "Losse pagina",
    privacyStatement: "Privacyvoorwaarden",
    menuPage: "Menu pagina",
    homePage: "Homepage",
    usageTerms: "Gebruikersvoorwaarden",
    editPage: "Pagina bewerken",
    default: "Standaard"

  },
  en: {
    save: "Save",
    savingInProgress: "The page is being saved, please wait.",
    savedSuccess: "The page has been saved.",
    pages: 'Pages',
    addPage: 'Add page',
    informExplain: 'Inform and explain',
    type: "Type",
    name: "Name",
    permalink: "Permalink",
    website: "Website",
    published: "Published",
    content: "Content",
    errorContent: "Please check if there is content for this page.",
    aboutUs: "About us",
    individualPage: "Individual page",
    privacyStatement: "Privacy Statement",
    menuPage: "Menu page",
    homePage: "Homepage",
    usageTerms: "Terms of use",
    editPage: "Edit page",
    default: "Default"
  },
};
